### PR TITLE
Added AssignedEmployees to Task

### PR DESCRIPTION
**Pull request by BryanL2303**
AssignedEmployees in Task functions just like AssignedTasks in Employee.

Whenever a task is assigned or unassigned both AssignedEmployees and AssignedTasks of the Task and Employee involved will be updated.

The UI for Task has also been updated to display the Employee ID and name of the employees that are assigned to the task.

### CODE REVIEW

**Comment by azumieflare** [comment]
LGTM. Can consider adding more test cases in future milestones to improve code coverage.

**Review by johnyoozhengxian — APPROVED** [review]
LGTM

**Review by johnyoozhengxian — APPROVED** [review]
LGTM

**Review by johnyoozhengxian — APPROVED** [review]
LGTM

**Review by johnyoozhengxian — APPROVED** [review]
LGTM

**Pull request merged**
